wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1689367267.230123
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 33
      - 40
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 33
      - 40
      - 53
      - 55
      3:
      - 1
      - 2
      - 13
      - 23
      4: 3.11.4
      5: 0.15.5
      8:
      - 1
      - 3
      - 5
